---
- name: Clone repository
  ansible.builtin.include_tasks:
    file: clone.yaml
    apply:
      vars:
        git_repository: "{{ git.repository }}"
        git_directory: "{{ git.directory }}"
  when: git.operation == "clone"

- name: Push Changes
  ansible.builtin.include_tasks:
    file: push.yaml
    apply:
      vars:
        git_repository: "{{ git.repository }}"
        git_directory: "{{ git.directory }}"
        git_message: "{{ git.message }}"
        git_email: "{{ git.email }}"
        git_user: "{{ git.user }}"
  when: git.operation == "push"
